name: autofix.ci
on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - main
permissions:
    contents: read

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - run: bun install
            - run: bun run lint --fix
            - uses: autofix-ci/action@7a166d7532b277f34e16238930461bf77f9d7ed8
