name: autofix.ci
on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - main
permissions:
    contents: read

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - run: bun install
            - run: bun run lint --fix
            - uses: autofix-ci/action@551dded8c6cc8a1054039c8bc0b8b48c51dfc6ef
